# Generated by Django 5.0.1 on 2025-11-10 11:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CITIZEN", "Citizen"),
                            ("ADMIN", "Administrator"),
                            ("DEPARTMENT_STAFF", "Department Staff"),
                        ],
                        default="CITIZEN",
                        max_length=20,
                    ),
                ),
                ("is_phone_verified", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ward",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A Ward - Colaba, Cuffe Parade"),
                            ("B", "B Ward - Dongri, Masjid Bunder"),
                            ("C", "C Ward - Marine Lines, Chandanwadi"),
                            ("D", "D Ward - Grant Road, Tardeo"),
                            ("E", "E Ward - Byculla, Mumbai Central"),
                            ("F/N", "F/North Ward - Matunga, Sion"),
                            ("F/S", "F/South Ward - Parel, Sewri"),
                            ("G/N", "G/North Ward - Dadar, Dharavi"),
                            ("G/S", "G/South Ward - Elphinstone Road"),
                            ("H/E", "H/East Ward - Bandra East, Khar East"),
                            ("H/W", "H/West Ward - Bandra West, Khar West"),
                            ("K/E", "K/East Ward - Andheri East"),
                            ("K/W", "K/West Ward - Andheri West, Versova"),
                            ("L", "L Ward - Kurla"),
                            ("M/E", "M/East Ward - Chembur East"),
                            ("M/W", "M/West Ward - Chembur West"),
                            ("N", "N Ward - Ghatkopar"),
                            ("P/N", "P/North Ward - Malad"),
                            ("P/S", "P/South Ward - Goregaon"),
                            ("R/C", "R/Central Ward - Borivali"),
                            ("R/N", "R/North Ward - Dahisar"),
                            ("R/S", "R/South Ward - Kandivali"),
                            ("S", "S Ward - Bhandup"),
                            ("T", "T Ward - Mulund"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("pincode", models.CharField(blank=True, max_length=6, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("EN", "English"), ("MR", "Marathi")],
                        default="EN",
                        max_length=2,
                    ),
                ),
                ("has_accepted_terms", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AdminRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("DEPARTMENT_STAFF", "Department Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Why this person should be granted admin access",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Registration Request",
                "verbose_name_plural": "Admin Registration Requests",
                "db_table": "admin_registration_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
