# Generated by Django 5.0.1 on 2025-11-12 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Officer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_ward",
                    models.CharField(
                        choices=[
                            ("A", "A Ward - Colaba, Cuffe Parade"),
                            ("B", "B Ward - Dongri, Masjid Bunder"),
                            ("C", "C Ward - Marine Lines, Chandanwadi"),
                            ("D", "D Ward - Grant Road, Tardeo"),
                            ("E", "E Ward - Byculla, Mumbai Central"),
                            ("F/N", "F/North Ward - Matunga, Sion"),
                            ("F/S", "F/South Ward - Parel, Sewri"),
                            ("G/N", "G/North Ward - Dadar, Dharavi"),
                            ("G/S", "G/South Ward - Elphinstone Road"),
                            ("H/E", "H/East Ward - Bandra East, Khar East"),
                            ("H/W", "H/West Ward - Bandra West, Khar West"),
                            ("K/E", "K/East Ward - Andheri East"),
                            ("K/W", "K/West Ward - Andheri West, Versova"),
                            ("L", "L Ward - Kurla"),
                            ("M/E", "M/East Ward - Chembur East"),
                            ("M/W", "M/West Ward - Chembur West"),
                            ("N", "N Ward - Ghatkopar"),
                            ("P/N", "P/North Ward - Malad"),
                            ("P/S", "P/South Ward - Goregaon"),
                            ("R/C", "R/Central Ward - Borivali"),
                            ("R/N", "R/North Ward - Dahisar"),
                            ("R/S", "R/South Ward - Kandivali"),
                            ("S", "S Ward - Bhandup"),
                            ("T", "T Ward - Mulund"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("DEPARTMENT_STAFF", "Department Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("complaints_handled", models.IntegerField(default=0)),
                (
                    "average_resolution_time",
                    models.FloatField(default=0.0, help_text="Average days to resolve"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officers",
                        to="departments.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "officers",
                "indexes": [
                    models.Index(
                        fields=["department"], name="officers_departm_ea8c53_idx"
                    ),
                    models.Index(
                        fields=["assigned_ward"], name="officers_assigne_8e8a16_idx"
                    ),
                    models.Index(fields=["role"], name="officers_role_54c027_idx"),
                ],
                "unique_together": {("user", "department")},
            },
        ),
    ]
