# Generated by Django 5.2.8 on 2025-12-05 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address used for login attempt', max_length=254)),
                ('success', models.BooleanField(default=False, help_text='Whether the login attempt was successful')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User agent string of the client')),
                ('failure_reason', models.CharField(blank=True, default='', help_text='Reason for failed login attempt', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', 'timestamp'], name='audit_login_email_8befa1_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_login_ip_addr_8dc769_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('CREATE_USER', 'User Created'), ('UPDATE_USER', 'User Updated'), ('DELETE_USER', 'User Deleted'), ('TOGGLE_USER_STATUS', 'User Status Toggled'), ('UPDATE_USER_STATUS', 'User Status Updated'), ('CREATE_COMPLAINT', 'Complaint Created'), ('UPDATE_COMPLAINT', 'Complaint Updated'), ('ASSIGN_COMPLAINT', 'Complaint Assigned'), ('CLOSE_COMPLAINT', 'Complaint Closed'), ('DELETE_COMPLAINT', 'Complaint Deleted'), ('GRANT_PERMISSION', 'Permission Granted'), ('REVOKE_PERMISSION', 'Permission Revoked'), ('CHANGE_ROLE', 'Role Changed'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete'), ('VIEW', 'View Resource'), ('EXPORT', 'Data Exported'), ('OTHER', 'Other Action')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('object_type', models.CharField(blank=True, default='', help_text='Type of object affected (e.g., User, Complaint)', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action (stored as JSON)')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Severity level of the action', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User agent string of the client')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
