# Generated by Django 5.0.1 on 2025-11-10 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("complaints", "0001_initial"),
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaintupdate",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaintupdate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["-created_at"], name="complaints_created_0cc0c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["status"], name="complaints_status_3d57ee_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["category"], name="complaints_categor_41c30d_idx"
            ),
        ),
    ]
