# Generated by Django 5.0.1 on 2025-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="ward",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
