# Generated by Django 5.0.1 on 2025-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_complaint_ward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="ward",
            field=models.CharField(max_length=10),
        ),
    ]
