# Generated by Django 5.2.8 on 2025-11-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_assigned_officer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='ai_category',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ai_confidence_score',
        ),
    ]
