# Generated by Django 5.2.8 on 2025-11-14 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaint_ai_category_and_more'),
        ('departments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('sla_target_days', models.IntegerField(default=7)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_assignments', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='complaints.complaint')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_assignments', to='departments.department')),
            ],
            options={
                'db_table': 'complaint_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['assigned_to', '-assigned_at'], name='complaint_a_assigne_6b8054_idx'), models.Index(fields=['complaint', 'assigned_at'], name='complaint_a_complai_372d4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplaintReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='complaints.complaint')),
                ('previously_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reassigned_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaint_reassignments',
                'ordering': ['-reassigned_at'],
                'indexes': [models.Index(fields=['complaint', '-reassigned_at'], name='complaint_r_complai_00bc3b_idx')],
            },
        ),
    ]
