# Generated by Django 5.2.8 on 2025-11-14 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaintassignment_complaintreassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assigned', models.IntegerField(default=0)),
                ('total_resolved', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('total_rejected', models.IntegerField(default=0)),
                ('sla_compliant_count', models.IntegerField(default=0)),
                ('sla_breached_count', models.IntegerField(default=0)),
                ('sla_compliance_rate', models.FloatField(default=0.0)),
                ('avg_resolution_time_hours', models.FloatField(default=0.0)),
                ('avg_resolution_time_days', models.FloatField(default=0.0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('five_star_count', models.IntegerField(default=0)),
                ('four_star_count', models.IntegerField(default=0)),
                ('three_star_count', models.IntegerField(default=0)),
                ('two_star_count', models.IntegerField(default=0)),
                ('one_star_count', models.IntegerField(default=0)),
                ('department_avg_rating', models.FloatField(default=0.0)),
                ('department_avg_resolution_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Officer Performance',
                'db_table': 'officer_performance',
            },
        ),
        migrations.CreateModel(
            name='OfficerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star - Very Poor'), (2, '2 Stars - Poor'), (3, '3 Stars - Average'), (4, '4 Stars - Good'), (5, '5 Stars - Excellent')])),
                ('comment', models.TextField(blank=True, help_text='Optional feedback from citizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_ratings', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_rating', to='complaints.complaint')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'officer_ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['officer', '-created_at'], name='officer_rat_officer_424983_idx'), models.Index(fields=['complaint'], name='officer_rat_complai_353d36_idx')],
                'unique_together': {('complaint', 'officer', 'citizen')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assigned', models.IntegerField()),
                ('total_resolved', models.IntegerField()),
                ('sla_compliance_rate', models.FloatField()),
                ('avg_resolution_time_hours', models.FloatField()),
                ('avg_rating', models.FloatField()),
                ('reason', models.CharField(help_text='Why these metrics were calculated', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['officer', '-created_at'], name='performance_officer_d36989_idx')],
            },
        ),
    ]
